### ISSUE TITLE
Some instructions & uses?

### ISSUE THREAD

**Issue by zhilyaev** [Flui/vue-vk#2]
I dont undestand how can I setup it and use it.
(I prefers use nuxt.js for developing)
```bash
npm install vue-vk
```
Thank you for help

**Comment by Antontsyk** [comment]
Hey!
How use VKcomments ?

**Comment by Antontsyk** [comment]
Привет, как интегрировать на страницу коменты?

**Comment by Flui** [comment]
Sorry that I did not answered yet. I will create a README

**Comment by voitsekhovskymax** [comment]
@Flui  Hello! I would like more component instructions 

> 
> 
> Sorry that I did not answered yet. I will create a README
